version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.2
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
